brand_health_index:
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      project: "{{ env_var('DBT_GOOGLE_BIGQUERY_PROJECT') }}"
      dataset: brand_health_dev
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      project: "{{ env_var('DBT_GOOGLE_BIGQUERY_PROJECT') }}"
      dataset: brand_health_prod
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1

  target: dev
